<?xml version = "1.0"?>
<!DOCTYPE Analyses [
<!ELEMENT Analyses (category*)>

<!ELEMENT category (app+)>
<!ATTLIST category
    name     CDATA #REQUIRED>

<!ELEMENT app EMPTY>
<!ATTLIST app
    name     CDATA #REQUIRED
    module   CDATA "sowa"
    xml      CDATA #IMPLIED
    desc     CDATA #IMPLIED>
]>

<!--
    Cembalo Generator (ACD -> XML), for Soaplab2
    Version $Id: acd2xml,v 1.28 2010/08/10 10:55:42 marsenger Exp $
    Contact: Martin Senger <martin.senger@gmail.com>

    This file was generated: Tue Mar  4 10:36:48 CET 2025

    This file contains a list of applications which are available
    from a Soaplab2 server.
-->

<Analyses>
    <category
        name = "alignment"
        >
        <app
            name = "extractalign"
            xml = "./alignment/extractalign_al.xml"
            desc = "Extract regions from a sequence alignment"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
    </category>
    <category
        name = "alignment_consensus"
        >
        <app
            name = "cons"
            xml = "./alignment_consensus/cons_al.xml"
            desc = "Create a consensus sequence from a multiple alignment"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "consambig"
            xml = "./alignment_consensus/consambig_al.xml"
            desc = "Create an ambiguous consensus sequence from a multiple alignment"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "megamerger"
            xml = "./alignment_consensus/megamerger_al.xml"
            desc = "Merge two large overlapping DNA sequences"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "merger"
            xml = "./alignment_consensus/merger_al.xml"
            desc = "Merge two overlapping sequences"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
    </category>
    <category
        name = "alignment_differences"
        >
        <app
            name = "diffseq"
            xml = "./alignment_differences/diffseq_al.xml"
            desc = "Compare and report features of two similar sequences"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
    </category>
    <category
        name = "alignment_dot_plots"
        >
        <app
            name = "dotmatcher"
            xml = "./alignment_dot_plots/dotmatcher_al.xml"
            desc = "Draw a threshold dotplot of two sequences"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "dotpath"
            xml = "./alignment_dot_plots/dotpath_al.xml"
            desc = "Draw a non-overlapping wordmatch dotplot of two sequences"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "dottup"
            xml = "./alignment_dot_plots/dottup_al.xml"
            desc = "Display a wordmatch dotplot of two sequences"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "polydot"
            xml = "./alignment_dot_plots/polydot_al.xml"
            desc = "Draw dotplots for all-against-all comparison of a sequence set"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
    </category>
    <category
        name = "alignment_global"
        >
        <app
            name = "est2genome"
            xml = "./alignment_global/est2genome_al.xml"
            desc = "Align EST sequences to genomic DNA sequence"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "needle"
            xml = "./alignment_global/needle_al.xml"
            desc = "Needleman-Wunsch global alignment of two sequences"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "needleall"
            xml = "./alignment_global/needleall_al.xml"
            desc = "Many-to-many pairwise alignments of two sequence sets"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "stretcher"
            xml = "./alignment_global/stretcher_al.xml"
            desc = "Needleman-Wunsch rapid global alignment of two sequences"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
    </category>
    <category
        name = "alignment_local"
        >
        <app
            name = "matcher"
            xml = "./alignment_local/matcher_al.xml"
            desc = "Waterman-Eggert local alignment of two sequences"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "seqmatchall"
            xml = "./alignment_local/seqmatchall_al.xml"
            desc = "All-against-all word comparison of a sequence set"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "supermatcher"
            xml = "./alignment_local/supermatcher_al.xml"
            desc = "Calculate approximate local pair-wise alignments of larger sequences"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "water"
            xml = "./alignment_local/water_al.xml"
            desc = "Smith-Waterman local alignment of sequences"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "wordfinder"
            xml = "./alignment_local/wordfinder_al.xml"
            desc = "Match large sequences against one or more other sequences"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "wordmatch"
            xml = "./alignment_local/wordmatch_al.xml"
            desc = "Find regions of identity (exact matches) of two sequences"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
    </category>
    <category
        name = "alignment_multiple"
        >
        <app
            name = "edialign"
            xml = "./alignment_multiple/edialign_al.xml"
            desc = "Local multiple alignment of sequences"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "emma"
            xml = "./alignment_multiple/emma_al.xml"
            desc = "Multiple sequence alignment (ClustalW wrapper)"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "infoalign"
            xml = "./alignment_multiple/infoalign_al.xml"
            desc = "Display basic information about a multiple sequence alignment"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "plotcon"
            xml = "./alignment_multiple/plotcon_al.xml"
            desc = "Plot conservation of a sequence alignment"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "prettyplot"
            xml = "./alignment_multiple/prettyplot_al.xml"
            desc = "Draw a sequence alignment with pretty formatting"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "showalign"
            xml = "./alignment_multiple/showalign_al.xml"
            desc = "Display a multiple sequence alignment in pretty format"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "tranalign"
            xml = "./alignment_multiple/tranalign_al.xml"
            desc = "Generate an alignment of nucleic coding regions from aligned proteins"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
    </category>
    <category
        name = "data_resources"
        >
        <app
            name = "cachedas"
            xml = "./data_resources/cachedas_al.xml"
            desc = "Generate server cache file for DAS servers or for the DAS registry"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "cachedbfetch"
            xml = "./data_resources/cachedbfetch_al.xml"
            desc = "Generate server cache file for Dbfetch/WSDbfetch data sources"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "cacheebeyesearch"
            xml = "./data_resources/cacheebeyesearch_al.xml"
            desc = "Generate server cache file for EB-eye search domains"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "cacheensembl"
            xml = "./data_resources/cacheensembl_al.xml"
            desc = "Generate server cache file for an Ensembl server"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "dbtell"
            xml = "./data_resources/dbtell_al.xml"
            desc = "Display information about a public database"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "servertell"
            xml = "./data_resources/servertell_al.xml"
            desc = "Display information about a public server"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "showdb"
            xml = "./data_resources/showdb_al.xml"
            desc = "Display information on configured databases"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "showserver"
            xml = "./data_resources/showserver_al.xml"
            desc = "Display information on configured servers"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
    </category>
    <category
        name = "data_retrieval"
        >
        <app
            name = "codcopy"
            xml = "./data_retrieval/codcopy_al.xml"
            desc = "Copy and reformat a codon usage table"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "seqret"
            xml = "./data_retrieval/seqret_al.xml"
            desc = "Read and write (return) sequences"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
    </category>
    <category
        name = "data_retrieval_chemistry_data"
        >
        <app
            name = "infobase"
            xml = "./data_retrieval_chemistry_data/infobase_al.xml"
            desc = "Return information on a given nucleotide base"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "inforesidue"
            xml = "./data_retrieval_chemistry_data/inforesidue_al.xml"
            desc = "Return information on a given amino acid residue"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
    </category>
    <category
        name = "data_retrieval_feature_data"
        >
        <app
            name = "featcopy"
            xml = "./data_retrieval_feature_data/featcopy_al.xml"
            desc = "Read and write a feature table"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "featmerge"
            xml = "./data_retrieval_feature_data/featmerge_al.xml"
            desc = "Merge two overlapping feature tables"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
    </category>
    <category
        name = "data_retrieval_ontology_data"
        >
        <app
            name = "edamdef"
            xml = "./ontology_edam/edamdef_al.xml"
            desc = "Find EDAM ontology terms by definition"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "edamhasinput"
            xml = "./ontology_edam/edamhasinput_al.xml"
            desc = "Find EDAM ontology terms by has_input relation"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "edamhasoutput"
            xml = "./ontology_edam/edamhasoutput_al.xml"
            desc = "Find EDAM ontology terms by has_output relation"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "edamisformat"
            xml = "./ontology_edam/edamisformat_al.xml"
            desc = "Find EDAM ontology terms by is_format_of relation"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "edamisid"
            xml = "./ontology_edam/edamisid_al.xml"
            desc = "Find EDAM ontology terms by is_identifier_of relation"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "edamname"
            xml = "./ontology_edam/edamname_al.xml"
            desc = "Find EDAM ontology terms by name"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "godef"
            xml = "./ontology_go/godef_al.xml"
            desc = "Find GO ontology terms by definition"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "goname"
            xml = "./ontology_go/goname_al.xml"
            desc = "Find GO ontology terms by name"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "ontoget"
            xml = "./ontology/ontoget_al.xml"
            desc = "Get ontology term(s)"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "ontogetcommon"
            xml = "./ontology/ontogetcommon_al.xml"
            desc = "Get common ancestor for terms"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "ontogetdown"
            xml = "./ontology/ontogetdown_al.xml"
            desc = "Get ontology term(s) by parent id"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "ontogetobsolete"
            xml = "./ontology/ontogetobsolete_al.xml"
            desc = "Get ontology ontology terms"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "ontogetroot"
            xml = "./ontology/ontogetroot_al.xml"
            desc = "Get ontology root terms by child identifier"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "ontogetsibs"
            xml = "./ontology/ontogetsibs_al.xml"
            desc = "Get ontology term(s) by id with common parent"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "ontogetup"
            xml = "./ontology/ontogetup_al.xml"
            desc = "Get ontology term(s) by id of child"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "ontoisobsolete"
            xml = "./ontology/ontoisobsolete_al.xml"
            desc = "Report whether an ontology term id is obsolete"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "ontotext"
            xml = "./ontology/ontotext_al.xml"
            desc = "Get ontology term(s) original full text"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
    </category>
    <category
        name = "data_retrieval_resource_data"
        >
        <app
            name = "drfinddata"
            xml = "./ontology_edam/drfinddata_al.xml"
            desc = "Find public databases by data type"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "drfindformat"
            xml = "./ontology_edam/drfindformat_al.xml"
            desc = "Find public databases by format"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "drfindid"
            xml = "./ontology_edam/drfindid_al.xml"
            desc = "Find public databases by identifier"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "drfindresource"
            xml = "./ontology_edam/drfindresource_al.xml"
            desc = "Find public databases by resource"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "drget"
            xml = "./data_retrieval_resource_data/drget_al.xml"
            desc = "Get data resource entries"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "drtext"
            xml = "./data_retrieval_resource_data/drtext_al.xml"
            desc = "Get data resource entries complete text"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
    </category>
    <category
        name = "data_retrieval_sequence_data"
        >
        <app
            name = "coderet"
            xml = "./nucleic_translation/coderet_al.xml"
            desc = "Extract CDS, mRNA and translations from feature tables"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "entret"
            xml = "./edit/entret_al.xml"
            desc = "Retrieve sequence entries from flatfile databases and files"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "extractalign"
            xml = "./alignment/extractalign_al.xml"
            desc = "Extract regions from a sequence alignment"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "infoalign"
            xml = "./alignment_multiple/infoalign_al.xml"
            desc = "Display basic information about a multiple sequence alignment"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "infoseq"
            xml = "./data_retrieval_sequence_data/infoseq_al.xml"
            desc = "Display basic information about sequences"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "refseqget"
            xml = "./data_retrieval_sequence_data/refseqget_al.xml"
            desc = "Get reference sequence"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "seqxref"
            xml = "./data_retrieval_sequence_data/seqxref_al.xml"
            desc = "Retrieve all database cross-references for a sequence entry"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "seqxrefget"
            xml = "./data_retrieval_sequence_data/seqxrefget_al.xml"
            desc = "Retrieve all cross-referenced data for a sequence entry"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "showalign"
            xml = "./alignment_multiple/showalign_al.xml"
            desc = "Display a multiple sequence alignment in pretty format"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "whichdb"
            xml = "./data_retrieval_sequence_data/whichdb_al.xml"
            desc = "Search all sequence databases for an entry and retrieve it"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
    </category>
    <category
        name = "data_retrieval_sequence_data_assembly_data"
        >
        <app
            name = "assemblyget"
            xml = "./data_retrieval_sequence_data_assembly_data/assemblyget_al.xml"
            desc = "Get assembly of sequence reads"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "infoassembly"
            xml = "./data_retrieval_sequence_data_assembly_data/infoassembly_al.xml"
            desc = "Display information about assemblies"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
    </category>
    <category
        name = "data_retrieval_text_data"
        >
        <app
            name = "drtext"
            xml = "./data_retrieval_resource_data/drtext_al.xml"
            desc = "Get data resource entries complete text"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "entret"
            xml = "./edit/entret_al.xml"
            desc = "Retrieve sequence entries from flatfile databases and files"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "ontotext"
            xml = "./ontology/ontotext_al.xml"
            desc = "Get ontology term(s) original full text"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "textget"
            xml = "./data_retrieval_text_data/textget_al.xml"
            desc = "Get text data entries"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "textsearch"
            xml = "./data_retrieval_text_data/textsearch_al.xml"
            desc = "Search the textual description of sequence(s)"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
    </category>
    <category
        name = "display"
        >
        <app
            name = "cirdna"
            xml = "./display/cirdna_al.xml"
            desc = "Draw circular map of DNA constructs"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "iep"
            xml = "./protein_properties/iep_al.xml"
            desc = "Calculate the isoelectric point of proteins"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "lindna"
            xml = "./display/lindna_al.xml"
            desc = "Draw linear maps of DNA constructs"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "pepinfo"
            xml = "./protein_composition/pepinfo_al.xml"
            desc = "Plot amino acid properties of a protein sequence in parallel."
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "pepnet"
            xml = "./display/pepnet_al.xml"
            desc = "Draw a helical net for a protein sequence"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "pepwheel"
            xml = "./display/pepwheel_al.xml"
            desc = "Draw a helical wheel diagram for a protein sequence"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "plotorf"
            xml = "./nucleic_gene_finding/plotorf_al.xml"
            desc = "Plot potential open reading frames in a nucleotide sequence"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "prettyplot"
            xml = "./alignment_multiple/prettyplot_al.xml"
            desc = "Draw a sequence alignment with pretty formatting"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "prettyseq"
            xml = "./nucleic_translation/prettyseq_al.xml"
            desc = "Write a nucleotide sequence and its translation to file"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "remap"
            xml = "./display/remap_al.xml"
            desc = "Display restriction enzyme binding sites in a nucleotide sequence"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "showfeat"
            xml = "./display/showfeat_al.xml"
            desc = "Display features of a sequence in pretty format"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "showpep"
            xml = "./display/showpep_al.xml"
            desc = "Display protein sequences with features in pretty format"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "sixpack"
            xml = "./nucleic_gene_finding/sixpack_al.xml"
            desc = "Display a DNA sequence with 6-frame translation and ORFs"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
    </category>
    <category
        name = "documentation"
        >
        <app
            name = "seealso"
            xml = "./documentation/seealso_al.xml"
            desc = "Find programs with similar function to a specified program"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "tfm"
            xml = "./documentation/tfm_al.xml"
            desc = "Display full documentation for an application"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "wossdata"
            xml = "./ontology_edam/wossdata_al.xml"
            desc = "Find programs by EDAM data"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "wossinput"
            xml = "./ontology_edam/wossinput_al.xml"
            desc = "Find programs by EDAM input data"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "wossname"
            xml = "./documentation/wossname_al.xml"
            desc = "Find programs by keywords in their short description"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "wossoperation"
            xml = "./ontology_edam/wossoperation_al.xml"
            desc = "Find programs by EDAM operation"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "wossoutput"
            xml = "./ontology_edam/wossoutput_al.xml"
            desc = "Find programs by EDAM output data"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "wossparam"
            xml = "./ontology_edam/wossparam_al.xml"
            desc = "Find programs by EDAM parameter"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "wosstopic"
            xml = "./ontology_edam/wosstopic_al.xml"
            desc = "Find programs by EDAM topic"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
    </category>
    <category
        name = "edit"
        >
        <app
            name = "aligncopy"
            xml = "./edit/aligncopy_al.xml"
            desc = "Read and write alignments"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "aligncopypair"
            xml = "./edit/aligncopypair_al.xml"
            desc = "Read and write pairs from alignments"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "biosed"
            xml = "./edit/biosed_al.xml"
            desc = "Replace or delete sequence sections"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "codcopy"
            xml = "./data_retrieval/codcopy_al.xml"
            desc = "Copy and reformat a codon usage table"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "cutseq"
            xml = "./edit/cutseq_al.xml"
            desc = "Remove a section from a sequence"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "degapseq"
            xml = "./edit/degapseq_al.xml"
            desc = "Remove non-alphabetic (e.g. gap) characters from sequences"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "descseq"
            xml = "./edit/descseq_al.xml"
            desc = "Alter the name or description of a sequence."
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "entret"
            xml = "./edit/entret_al.xml"
            desc = "Retrieve sequence entries from flatfile databases and files"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "extractalign"
            xml = "./alignment/extractalign_al.xml"
            desc = "Extract regions from a sequence alignment"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "extractfeat"
            xml = "./edit/extractfeat_al.xml"
            desc = "Extract features from sequence(s)"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "extractseq"
            xml = "./edit/extractseq_al.xml"
            desc = "Extract regions from a sequence"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "featcopy"
            xml = "./data_retrieval_feature_data/featcopy_al.xml"
            desc = "Read and write a feature table"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "featmerge"
            xml = "./data_retrieval_feature_data/featmerge_al.xml"
            desc = "Merge two overlapping feature tables"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app
            name = "featreport"
            xml = "./edit/featreport_al.xml"
            desc = "Read and write a feature table"
            module = "org.soaplab.emboss.EmbossJobFactory"
            />
        <app